#version 450

// Adapted from AOCE (MIT); see AOCE_LICENSE.txt.
layout (local_size_x = 16, local_size_y = 16) in;

layout (binding = 0, rgba16f) uniform readonly image2D inTex;
layout (binding = 1, rgba16f) uniform writeonly image2D outTex;

layout (std140, binding = 2) uniform FalseColorParams {
    float firstColorR;
    float firstColorG;
    float firstColorB;
    float secondColorR;
    float secondColorG;
    float secondColorB;
} params;

const vec3 LUMINANCE_BT2020 = vec3(0.2627, 0.6780, 0.0593);

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(inTex);
    if (pixel.x >= size.x || pixel.y >= size.y) return;

    vec4 color = imageLoad(inTex, pixel);
    vec3 firstColor = vec3(params.firstColorR,
                           params.firstColorG,
                           params.firstColorB);
    vec3 secondColor = vec3(params.secondColorR,
                            params.secondColorG,
                            params.secondColorB);
    float luminance = clamp(dot(color.rgb, LUMINANCE_BT2020), 0.0, 1.0);
    imageStore(outTex, pixel,
               vec4(mix(firstColor, secondColor, luminance), color.a));
}
