#version 450

// Preserves AOCE's source-over interpolation behavior.
// Adapted from AOCE (MIT); see AOCE_LICENSE.txt.
layout (local_size_x = 16, local_size_y = 16) in;

layout (binding = 0, rgba16f) uniform readonly image2D baseTex;
layout (binding = 1, rgba16f) uniform readonly image2D layerTex;
layout (binding = 2, rgba16f) uniform writeonly image2D outTex;

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outTex);
    if (pixel.x >= size.x || pixel.y >= size.y) return;

    vec4 base = imageLoad(baseTex, pixel);
    vec4 layer = imageLoad(layerTex, pixel);
    imageStore(outTex, pixel, mix(base, layer, layer.a));
}

